# Form implementation generated from reading ui file 'g:\Documents\PyQt\302\A\views\authorForm.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_newAuthor(object):
    def setupUi(self, newAuthor):
        newAuthor.setObjectName("newAuthor")
        newAuthor.resize(312, 342)
        self.centralwidget = QtWidgets.QWidget(parent=newAuthor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelNewAuthor = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelNewAuthor.setFont(font)
        self.labelNewAuthor.setObjectName("labelNewAuthor")
        self.gridLayout.addWidget(self.labelNewAuthor, 0, 0, 1, 1)
        self.labelFirstName = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelFirstName.setFont(font)
        self.labelFirstName.setObjectName("labelFirstName")
        self.gridLayout.addWidget(self.labelFirstName, 1, 0, 1, 1)
        self.inputFirstName = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputFirstName.setFont(font)
        self.inputFirstName.setObjectName("inputFirstName")
        self.gridLayout.addWidget(self.inputFirstName, 2, 0, 1, 2)
        self.labelLastName = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelLastName.setFont(font)
        self.labelLastName.setObjectName("labelLastName")
        self.gridLayout.addWidget(self.labelLastName, 3, 0, 1, 1)
        self.inputLastName = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputLastName.setFont(font)
        self.inputLastName.setObjectName("inputLastName")
        self.gridLayout.addWidget(self.inputLastName, 4, 0, 1, 2)
        self.createAuthorBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createAuthorBtn.setFont(font)
        self.createAuthorBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.createAuthorBtn.setObjectName("createAuthorBtn")
        self.gridLayout.addWidget(self.createAuthorBtn, 5, 1, 1, 1)
        newAuthor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=newAuthor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 312, 26))
        self.menubar.setObjectName("menubar")
        newAuthor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=newAuthor)
        self.statusbar.setObjectName("statusbar")
        newAuthor.setStatusBar(self.statusbar)

        self.retranslateUi(newAuthor)
        QtCore.QMetaObject.connectSlotsByName(newAuthor)

    def retranslateUi(self, newAuthor):
        _translate = QtCore.QCoreApplication.translate
        newAuthor.setWindowTitle(_translate("newAuthor", "Create A new Author"))
        self.labelNewAuthor.setText(_translate("newAuthor", "New Author"))
        self.labelFirstName.setText(_translate("newAuthor", "First Name"))
        self.labelLastName.setText(_translate("newAuthor", "Last Name"))
        self.createAuthorBtn.setStatusTip(_translate("newAuthor", "Submit form to create new author..."))
        self.createAuthorBtn.setText(_translate("newAuthor", "Submit"))
