# Form implementation generated from reading ui file 'g:\Documents\PyQt\final_project\views\adminDashboard.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_adminDashboard(object):
    def setupUi(self, adminDashboard):
        adminDashboard.setObjectName("adminDashboard")
        adminDashboard.resize(352, 364)
        self.verticalLayout = QtWidgets.QVBoxLayout(adminDashboard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainHeader = QtWidgets.QLabel(parent=adminDashboard)
        self.mainHeader.setObjectName("mainHeader")
        self.verticalLayout.addWidget(self.mainHeader)
        self.newUserBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.newUserBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.newUserBtn.setObjectName("newUserBtn")
        self.verticalLayout.addWidget(self.newUserBtn)
        self.editUserBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.editUserBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.editUserBtn.setObjectName("editUserBtn")
        self.verticalLayout.addWidget(self.editUserBtn)
        spacerItem = QtWidgets.QSpacerItem(327, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.newTaskBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.newTaskBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.newTaskBtn.setObjectName("newTaskBtn")
        self.verticalLayout.addWidget(self.newTaskBtn)
        self.editTaskBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.editTaskBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.editTaskBtn.setObjectName("editTaskBtn")
        self.verticalLayout.addWidget(self.editTaskBtn)
        spacerItem1 = QtWidgets.QSpacerItem(327, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.choreManagerBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.choreManagerBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.choreManagerBtn.setObjectName("choreManagerBtn")
        self.verticalLayout.addWidget(self.choreManagerBtn)

        self.retranslateUi(adminDashboard)
        QtCore.QMetaObject.connectSlotsByName(adminDashboard)

    def retranslateUi(self, adminDashboard):
        _translate = QtCore.QCoreApplication.translate
        adminDashboard.setWindowTitle(_translate("adminDashboard", "Admin Dashboard"))
        self.mainHeader.setText(_translate("adminDashboard", "Welcome Admin User"))
        self.newUserBtn.setText(_translate("adminDashboard", "Create New User"))
        self.editUserBtn.setText(_translate("adminDashboard", "Edit User"))
        self.newTaskBtn.setText(_translate("adminDashboard", "Create new Task"))
        self.editTaskBtn.setText(_translate("adminDashboard", "Edit Task"))
        self.choreManagerBtn.setText(_translate("adminDashboard", "Open Chore Manager"))
