# Form implementation generated from reading ui file 'g:\Documents\PyQt\final_project\views\adminDashboard.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_adminDashboard(object):
    def setupUi(self, adminDashboard):
        adminDashboard.setObjectName("adminDashboard")
        adminDashboard.resize(356, 373)
        self.mainHeader = QtWidgets.QLabel(parent=adminDashboard)
        self.mainHeader.setGeometry(QtCore.QRect(10, 10, 331, 31))
        self.mainHeader.setObjectName("mainHeader")
        self.newChoreBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.newChoreBtn.setGeometry(QtCore.QRect(10, 60, 331, 41))
        self.newChoreBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.newChoreBtn.setObjectName("newChoreBtn")
        self.newTaskBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.newTaskBtn.setGeometry(QtCore.QRect(10, 110, 331, 41))
        self.newTaskBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.newTaskBtn.setObjectName("newTaskBtn")
        self.newUserBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.newUserBtn.setGeometry(QtCore.QRect(10, 160, 331, 41))
        self.newUserBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.newUserBtn.setObjectName("newUserBtn")
        self.editChoreBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.editChoreBtn.setGeometry(QtCore.QRect(10, 210, 331, 41))
        self.editChoreBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.editChoreBtn.setObjectName("editChoreBtn")
        self.editTaskBtn = QtWidgets.QPushButton(parent=adminDashboard)
        self.editTaskBtn.setGeometry(QtCore.QRect(10, 260, 331, 41))
        self.editTaskBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.editTaskBtn.setObjectName("editTaskBtn")
        self.editUser = QtWidgets.QPushButton(parent=adminDashboard)
        self.editUser.setGeometry(QtCore.QRect(10, 310, 331, 41))
        self.editUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.editUser.setObjectName("editUser")

        self.retranslateUi(adminDashboard)
        QtCore.QMetaObject.connectSlotsByName(adminDashboard)

    def retranslateUi(self, adminDashboard):
        _translate = QtCore.QCoreApplication.translate
        adminDashboard.setWindowTitle(_translate("adminDashboard", "Admin Dashboard"))
        self.mainHeader.setText(_translate("adminDashboard", "Welcome Admin User"))
        self.newChoreBtn.setText(_translate("adminDashboard", "Create New Chore"))
        self.newTaskBtn.setText(_translate("adminDashboard", "Create new Task"))
        self.newUserBtn.setText(_translate("adminDashboard", "Create New User"))
        self.editChoreBtn.setText(_translate("adminDashboard", "Edit Chore"))
        self.editTaskBtn.setText(_translate("adminDashboard", "Edit Task"))
        self.editUser.setText(_translate("adminDashboard", "Edit User"))
