# Form implementation generated from reading ui file 'g:\Documents\PyQt\final_project\views\main.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(688, 689)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainHeader = QtWidgets.QLabel(parent=self.centralwidget)
        self.mainHeader.setGeometry(QtCore.QRect(20, 10, 321, 51))
        self.mainHeader.setObjectName("mainHeader")
        self.notesHeader = QtWidgets.QLabel(parent=self.centralwidget)
        self.notesHeader.setGeometry(QtCore.QRect(20, 380, 321, 41))
        self.notesHeader.setObjectName("notesHeader")
        self.notesDisplay = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.notesDisplay.setGeometry(QtCore.QRect(20, 430, 321, 181))
        self.notesDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.notesDisplay.setObjectName("notesDisplay")
        self.choreList = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.choreList.setGeometry(QtCore.QRect(20, 50, 321, 331))
        self.choreList.setObjectName("choreList")
        self.choreList.setColumnCount(0)
        self.choreList.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 26))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(parent=self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.showCalculator = QtGui.QAction(parent=MainWindow)
        self.showCalculator.setObjectName("showCalculator")
        self.enterAdmin = QtGui.QAction(parent=MainWindow)
        self.enterAdmin.setObjectName("enterAdmin")
        self.menuTools.addAction(self.showCalculator)
        self.menuTools.addAction(self.enterAdmin)
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Family Planner"))
        self.mainHeader.setText(_translate("MainWindow", "Your Chores"))
        self.notesHeader.setText(_translate("MainWindow", "Speacil Notes"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.showCalculator.setText(_translate("MainWindow", "Calculator"))
        self.enterAdmin.setText(_translate("MainWindow", "Enter Admin"))
