# Form implementation generated from reading ui file 'g:\Documents\PyQt\final_project\views\updateObjSelect.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_selectObjWindow(object):
    def setupUi(self, selectObjWindow):
        selectObjWindow.setObjectName("selectObjWindow")
        selectObjWindow.resize(406, 183)
        self.mainHeader = QtWidgets.QLabel(parent=selectObjWindow)
        self.mainHeader.setGeometry(QtCore.QRect(20, 20, 231, 31))
        self.mainHeader.setObjectName("mainHeader")
        self.objInput = QtWidgets.QComboBox(parent=selectObjWindow)
        self.objInput.setGeometry(QtCore.QRect(20, 60, 361, 41))
        self.objInput.setObjectName("objInput")
        self.submitBtn = QtWidgets.QPushButton(parent=selectObjWindow)
        self.submitBtn.setGeometry(QtCore.QRect(252, 120, 121, 31))
        self.submitBtn.setObjectName("submitBtn")
        self.deleteBtn = QtWidgets.QPushButton(parent=selectObjWindow)
        self.deleteBtn.setGeometry(QtCore.QRect(30, 120, 111, 31))
        self.deleteBtn.setObjectName("deleteBtn")

        self.retranslateUi(selectObjWindow)
        QtCore.QMetaObject.connectSlotsByName(selectObjWindow)

    def retranslateUi(self, selectObjWindow):
        _translate = QtCore.QCoreApplication.translate
        selectObjWindow.setWindowTitle(_translate("selectObjWindow", "Update"))
        self.mainHeader.setText(_translate("selectObjWindow", "Select One"))
        self.submitBtn.setText(_translate("selectObjWindow", "Select"))
        self.deleteBtn.setText(_translate("selectObjWindow", "Delete User"))
