# Form implementation generated from reading ui file 'g:\Documents\PyQt\302\A copy\views\bookForm.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_newBook(object):
    def setupUi(self, newBook):
        newBook.setObjectName("newBook")
        newBook.resize(326, 368)
        self.centralwidget = QtWidgets.QWidget(parent=newBook)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lableNewBook = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lableNewBook.setFont(font)
        self.lableNewBook.setObjectName("lableNewBook")
        self.gridLayout.addWidget(self.lableNewBook, 0, 0, 1, 1)
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 1, 0, 1, 1)
        self.inputTitle = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputTitle.setFont(font)
        self.inputTitle.setObjectName("inputTitle")
        self.gridLayout.addWidget(self.inputTitle, 2, 0, 1, 2)
        self.labelPages = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPages.setFont(font)
        self.labelPages.setObjectName("labelPages")
        self.gridLayout.addWidget(self.labelPages, 3, 0, 1, 1)
        self.inputPages = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputPages.setFont(font)
        self.inputPages.setObjectName("inputPages")
        self.gridLayout.addWidget(self.inputPages, 4, 0, 1, 2)
        self.labelAuthor = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAuthor.setFont(font)
        self.labelAuthor.setObjectName("labelAuthor")
        self.gridLayout.addWidget(self.labelAuthor, 5, 0, 1, 1)
        self.inputAuthor = QtWidgets.QComboBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputAuthor.setFont(font)
        self.inputAuthor.setObjectName("inputAuthor")
        self.gridLayout.addWidget(self.inputAuthor, 6, 0, 1, 2)
        self.createBookBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createBookBtn.setFont(font)
        self.createBookBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.createBookBtn.setObjectName("createBookBtn")
        self.gridLayout.addWidget(self.createBookBtn, 7, 1, 1, 1)
        newBook.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=newBook)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 326, 26))
        self.menubar.setObjectName("menubar")
        newBook.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=newBook)
        self.statusbar.setObjectName("statusbar")
        newBook.setStatusBar(self.statusbar)

        self.retranslateUi(newBook)
        QtCore.QMetaObject.connectSlotsByName(newBook)

    def retranslateUi(self, newBook):
        _translate = QtCore.QCoreApplication.translate
        newBook.setWindowTitle(_translate("newBook", "Create A New Book"))
        self.lableNewBook.setText(_translate("newBook", "New Book"))
        self.labelTitle.setText(_translate("newBook", "Title"))
        self.labelPages.setText(_translate("newBook", "Pages"))
        self.labelAuthor.setText(_translate("newBook", "Author"))
        self.createBookBtn.setStatusTip(_translate("newBook", "Submit form to create new book..."))
        self.createBookBtn.setText(_translate("newBook", "Submit"))
